### PR TITLE
Possibly maybe fix after update?

### PR DESCRIPTION
**Pull request by xADDBx**
The actual issue was that they added some Parameters to the Bark method, which made your Patch fail.

This only makes the mod load into the game without error. If the update otherwise broke the mod, please ignore this and close the PR

### CODE REVIEW

**Comment by xADDBx** [comment]
Using Aze.Publicize 👎

**Comment by Osmodium** [comment]
Thanks, I already had these changes locally and more,.

**Comment by Osmodium** [comment]
Thanks, I already had these changes locally and more,
Also what would you use instead of Aze.Publicize?

**Comment by xADDBx** [comment]
This is the latest csproj from the nuget [template](https://github.com/xADDBx/OwlcatNuGetTemplates/blob/main/content/RogueTrader.ModTemplate/%7BSourceName%7D/%7BSourceName%7D.csproj):
grafik

Notice the BepInEx.AssemblyPublicizer.MSBuild

With that, you only need to put Publicize="true" into the Reference itself.

There are some other improvements that have been made to the csproj; but that's that

**Comment by Osmodium** [comment]
Cool, I will give this a look, since Aze.Publicize is in my opinion clunky to use. Thanks!

**Pull request closed without merging**
